export let resultsData = {
    "requestTime": "2020-11-04T10:36:58.943197Z",
    "mailboxGuid": "027f1343-f105-48cf-a585-ca4040ea56f4",
    "tenantId": "72f988bf-86f1-41af-91ab-2d7cd011db47",
    "appId": "00000003-0000-0000-c000-000000000000",
    "deploymentRing": "SDFV2",
    "client": "Other REST clients",
    "entityCommand": "CreateEvent",
    "restAction": "POST-Events",
    "graphStatusCode": 400,
    "restStatus": "ClientError",
    "entityStatus": "BadRequest",
    "Latency": 29,
    "graphLog": {
        "env_name": "##IfxAggregatorService.LogEvent",
        "correlationId": "ef6c8921-890b-4cf6-9f0c-faa0e72e4971",
        "incomingUri": "me/events",
        "appId": "de8bc8b5-d9f9-48b1-a8ad-b748da725064",
        "tenantId": "72f988bf-86f1-41af-91ab-2d7cd011db47",
        "apiVersion": "v1.0",
        "message": "[Microsoft.Online.AggregatorService.Common.ServiceException: Your request can't be completed. The TransactionId specified in the request has already been used to create a different event.;   at Microsoft.Online.AggregatorService.Controller.SimpleRequest.<HandleWorkloadError>d__84.MoveNext() in X:\\bt\\1116722\\repo\\src\\dev\\Controller\\Requests\\SimpleRequest.cs:line 1524\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Online.AggregatorService.Controller.SimpleRequest.<DeserializeResponseStream>d__83.MoveNext() in X:\\bt\\1116722\\repo\\src\\dev\\Controller\\Requests\\SimpleRequest.cs:line 1483\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Online.AggregatorService.Controller.SimpleRequest.<ExecuteInternal>d__71.MoveNext() in X:\\bt\\1116722\\repo\\src\\dev\\Controller\\Requests\\SimpleRequest.cs:line 740\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Online.AggregatorService.Controller.SimpleRequestWithAutodiscover.<Execute>d__9.MoveNext() in X:\\bt\\1116722\\repo\\src\\dev\\Controller\\Requests\\SimpleRequestWithAutodiscover.cs:line 117\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Online.AggregatorService.Controller.RequestController.<HandleRequestInternal>d__14.MoveNext() in X:\\bt\\1116722\\repo\\src\\dev\\Controller\\Controllers\\RequestController.cs:line 155;]",
        "targetUri": "https://outlook.office.com/api/v2.0/Users('<key>')/Events",
        "outboundRequestId": "ba11ce1b-f5fb-4b98-bc4d-23da2e1961e7",
        "responseStatusCode": 400,
        "responseHeaders": "Transfer-Encoding=chunked;X-CalculatedFETarget=BL1PR13CU010.internal.ou;X-BackEndHttpStatus=400,400;X-FEProxyInfo=BL1PR13CA0280.NAMPRD13.P;X-CalculatedBETarget=MN2PR00MB0720.namprd00.p;X-RUM-Validated=1;X-BeSku=WCS6;x-ms-appId=00000003-0000-0000-c000-;x-ms-clientAppId=de8bc8b5-d9f9-48b1-a8ad-;Rate-Limit-Limit=10000;Rate-Limit-Remaining=9998;Rate-Limit-Reset=2020-11-04T10:46:50.344Z;OData-Version=4.0;X-DiagInfo=MN2PR00MB0720;X-BEServer=MN2PR00MB0720;X-Proxy-RoutingCorrectne=1;X-Proxy-BackendServerSta=400;X-FEServer=BL1PR13CA0280,MA1PR0101C;Date=Wed, 04 Nov 2020 10:36:5;Content-Type=application/json; odata.metadata=minimal; odata.streaming=true; IEEE754Compatible=false; charset=utf-8;Content-Length=367;",
        "requestMethod": "POST",
        "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36",
        "clientRequestHeader": "[Connection=keep-alive][Content-Length=485][Content-Type=application/json][Accept=*/*][Accept-Encoding=gzip, deflate, br][Accept-Language=en-US,en;q=0.9][Host=graph.microsoft.com][Referer=https://developer.micros][User-Agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36][sec-ch-ua=\"Chromium\";v=\"86\", \"\\\"No][SdkVersion=GraphExplorer/4.0, graph-js/2.1.0 (featureUsage=7)][sec-ch-ua-mobile=?0][client-request-id=5dec4ecd-d34d-3e9f-a817-fbc5fd1cc52b][Origin=https://developer.microsoft.com][Sec-Fetch-Site=same-site][Sec-Fetch-Mode=cors][Sec-Fetch-Dest=empty]"
    },
    "restLog": {
        "env_name": "##Microsoft.Office.Datacenter.PassiveMonitoring.ExoProtocolPassive.RestProtocolEvent",
        "env_cloud_name": "NAMPR00DG045",
        "env_cloud_role": "BE",
        "env_cloud_roleVer": "15.20.3582.0",
        "env_cloud_environment": "SDFV2",
        "env_cloud_location": "NAM",
        "env_cloud_deploymentUnit": "namprd00",
        "buildVersion": "15.20.3584.000",
        "TenantId": "72f988bf-86f1-41af-91ab-2d7cd011db47",
        "Action": "POST-Events",
        "ClientRequestId": "5dec4ecd-d34d-3e9f-a817-fbc5fd1cc52b",
        "RequestId": "ba11ce1b-f5fb-4b98-bc4d-23da2e1961e7",
        "ResultType": "ClientError",
        "ExceptionName": "Microsoft.Exchange.Entities.Calendaring.ClientIdAlreadyInUseException",
        "ExceptionDetails": "DispatchException=Microsoft.Exchange.Services.OData.ODataResponseException: Your request can't be completed. The TransactionId specified in the request has already been used to create a different event. ---> Microsoft.Exchange.Entities.Calendaring.ClientIdAlreadyInUseException: Your request can't be completed. The TransactionId specified in the request has already been used to create a different event.    at Microsoft.Exchange.Entities.Calendaring.EntitySets.EventCommands.CreateEventBase.ValidateCreationHash(Event eventWithKnownHash  Event otherEvent)    at Microsoft.Exchange.Entities.Calendaring.EntitySets.EventCommands.CreateSingleEventBase.InternalExecute()    at Microsoft.Exchange.Entities.Calendaring.EntitySets.EventCommands.CreateSingleEventBase.OnExecute()    at Microsoft.Exchange.Entities.EntitySets.Commands.Command`1.<>c__DisplayClass42_0.<Execute>b__0()    at Microsoft.Exchange.Entities.EntitySets.Commands.EntityCommand`2.ElevateIfNecessary(Action actionDelegate)    at Microsoft.Exchange.Entities.EntitySets.Commands.Command`1.Execute(CommandContext context)    at Microsoft.Exchange.Services.OData.Model.CreateEventCommandBase`2.InternalExecute(IExchangeService exchangeService)    --- End of inner exception stack trace ---    at Microsoft.Exchange.Services.OData.Model.CreateEventCommandBase`2.InternalExecute(IExchangeService exchangeService)    at Microsoft.Exchange.Services.OData.ExchangeServiceCommand`2.InternalExecute()    at Microsoft.Exchange.Services.OData.ODataCommand`2.Execute()    at Microsoft.Exchange.Services.OData.EntityContainersCommand`2.Execute()    at Microsoft.Exchange.OData.Web.BasicCommandExecutor.Execute()    at Microsoft.Exchange.Services.OData.Web.RequestBroker.Dispatch(AsyncCallback asyncCallback);",
        "ReturnCode": "ErrorDuplicateTransactionId",
        "AppId": "00000003-0000-0000-c000-000000000000",
        "ClientAppId": "de8bc8b5-d9f9-48b1-a8ad-b748da725064",
        "callerName": "BL1PR13CA0280.NAMPRD13.PROD.OUTLOOK.COM",
        "latencyMs": 29,
        "protocolStatusCode": "400"
    },
    "entityLog": {
        "env_name": "##Microsoft.Exchange.Data.Logging.EntityEvent",
        "env_time": "2020-11-04T10:36:58.943197Z",
        "env_cloud_name": "NAMPR00DG045",
        "env_cloud_environment": "SDFV2",
        "env_cloud_location": "NAM",
        "env_cloud_deploymentUnit": "namprd00",
        "ServerRequestId": "ba11ce1b-f5fb-4b98-bc4d-23da2e1961e7",
        "Command": "CreateEvent",
        "OrganizationId": "72f988bf-86f1-41af-91ab-2d7cd011db47",
        "MailboxGuid": "027f1343-f105-48cf-a585-ca4040ea56f4",
        "FolderId": "LgAAAADSZolR/zGmQaYL+w2LT9DPAQC8Y494AfO0S72HO5dunAAbAAAAAAENAAAC",
        "AppId": "00000003-0000-0000-c000-000000000000",
        "ClientInfoString": "Client=REST;Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36[AppId=de8bc8b5-d9f9-48b1-a8ad-b748da725064];",
        "ErrorCode": "ClientIdAlreadyInUseException",
        "Exception": "Microsoft.Exchange.Entities.Calendaring.ClientIdAlreadyInUseException: Your request can't be completed. The TransactionId specified in the request has already been used to create a different event.\r\n   at Microsoft.Exchange.Entities.Calendaring.EntitySets.EventCommands.CreateEventBase.ValidateCreationHash(Event eventWithKnownHash, Event otherEvent)\r\n   at Microsoft.Exchange.Entities.Calendaring.EntitySets.EventCommands.CreateSingleEventBase.InternalExecute()\r\n   at Microsoft.Exchange.Entities.Calendaring.EntitySets.EventCommands.CreateSingleEventBase.OnExecute()\r\n   at Microsoft.Exchange.Entities.EntitySets.Commands.Command`1.<>c__DisplayClass42_0.<Execute>b__0()",
        "CustomData": "{\"CommandContext\":\"[X-ExcludeRemoteCalendars:True]\"}",
        "ShortClientInfoString": "Other REST clients",
        "ResultCategory": "BadRequest",
        "buildVersion": "15.20.3584.000"
    }
};